### Set up coding environment
# Clear Data Sets & Plots
rm(list=ls())
set.seed(205)

# Load libraries
library(ggplot2)
library(maptools)
library(ks)
library(xlsx)

# Map paths
setwd('/Users/jmoore523/Dropbox/Graduate School/Q3 - Spring 2016/STATS205/Project/STATS205-DRCConflict')
input <- file.path(".", "Input")
output <- file.path(".", "Output")
temp <- file.path(".", "Temp")
log <- file.path(".", "Logs")

# Start Log
sink(paste0(log,"/05 Bootstrap CIs.txt"))

# Load data
load(file=paste0(temp,"/acleddrc.R"))
load(file=paste0(temp,"/drcgrid.R"))

# Subset data
acled.drc2015 <- subset(acled.drc, YEAR==2015)

### Function Definition
## Function to put data in format for surveillance plots
data.surveillance <- function(pointsbygridID, densitybygridID) {
  densitybygridID <- data.frame(densitybygridID)
  
  # Merge Data Sets
  pointsbygridID$ID <- as.character(pointsbygridID$ID)
  densitybygridID$ID <- as.character(densitybygridID$ID)
  dataforplot <- merge(pointsbygridID,densitybygridID, by="ID", all.y=TRUE)
  dataforplot$Freq[is.na(dataforplot$Freq)] <- 0
  names(dataforplot) <- c("ID","Events","EstimatedDensity")
  
  # Create CDF based on Density Estimates
  dataforplot <- dataforplot[order(-dataforplot$EstimatedDensity),]
  dataforplot$CumEvents <- cumsum(dataforplot$Events)
  cdf <- seq(1,nrow(dataforplot))/nrow(dataforplot)
  dataforplot <- cbind(dataforplot,cdf)
  
  # Convert cum events to percentage
  dataforplot$CumEvents <- dataforplot$CumEvents/sum(dataforplot$Events)
  
  return(dataforplot)
}

## Function to calculate AUC
calc.auc <- function(dataforauc) {
  dataforauc$ones <- rep(1,nrow(dataforauc))
  dataforauc$width <- dataforauc$ones/sum(dataforauc$ones)
  dataforauc$auccomp <- dataforauc$width*dataforauc$CumEvents
  sum(dataforauc$auccomp)
}

## Function to Perform Boostrap
B <- 10000
bootstrap.auc <- function(event.type="all", est.pi, est.lscv, est.lscv.RN, est.bcv1, est.ns) {
  ### Initialize AUC vectors for each bandwidth type
  auc.pi <- rep(0,B)
  auc.lscv <- rep(0,B)
  auc.lscv.RN <- rep(0,B)
  auc.bcv1 <- rep(0,B)
  auc.ns <- rep(0,B)
  
  ### Set Seed
  set.seed(205)
  
  ### Bootstrap
  for (i in 1:B) {
    print(i)
    # Subset data, if necessary
    if (event.type =="B") {
      acled.drc2015 <- subset(acled.drc2015, event_type_std=="Battle")
    }
    if (event.type == "R") {
      acled.drc2015.r <- subset(acled.drc2015, event_type_std=="Riots/Protests")
    }
    if (event.type == "V") {
      acled.drc2015.v <- subset(acled.drc2015, event_type_std=="Violence against civilians")
    }
    
    # Draw bootstrap sample
    ind <- sample(length(acled.drc2015), length(acled.drc2015), replace=TRUE)
    bs.samp <- acled.drc2015[ind,]
    row.names(bs.samp) <- seq(1,length(bs.samp))
    
    # Count Events
    points <- over(bs.samp, drcgrid)
    points.df <- as.data.frame(table(points$ID))
    names(points.df)[names(points.df)=="Var1"] <- "ID"
    
    # Calculate AUC for each bandwidth type
    surv.data <- data.surveillance(points.df, est.pi)
    new.auc <- calc.auc(surv.data)
    auc.pi[i] <- new.auc
    
    surv.data <- data.surveillance(points.df, est.lscv)
    new.auc <- calc.auc(surv.data)
    auc.lscv[i] <- new.auc
    
    surv.data <- data.surveillance(points.df, est.lscv.RN)
    new.auc <- calc.auc(surv.data)
    auc.lscv.RN[i] <- new.auc
    
    surv.data <- data.surveillance(points.df, est.bcv1)
    new.auc <- calc.auc(surv.data)
    auc.bcv1[i] <- new.auc
    
    surv.data <- data.surveillance(points.df, est.ns)
    new.auc <- calc.auc(surv.data)
    auc.ns[i] <- new.auc
  }
  df <- data.frame(cbind(auc.pi, auc.lscv, auc.lscv.RN, auc.bcv1, auc.ns))
  return(df)
}

## Function to Calculate CI
conflevel <- 0.95
lb.conf <- (1-conflevel)/(2*10)
ub.conf <- 1-lb.conf
bs.ci <- function(listofaucs) {
  lb <- quantile(listofaucs, probs = .005)
  avg <- mean(listofaucs)
  ub <- quantile(listofaucs, probs = .995)
  return(c(lb, avg, ub))
}

## Function to do Wilcoxon on AUCs
wilcox.auc <- function(df) {
  val <- rep(0,10)
  val[1] <- wilcox.test(df$auc.pi,df$auc.lscv)$p.value
  val[2] <- wilcox.test(df$auc.pi,df$auc.lscv.RN)$p.value
  val[3] <- wilcox.test(df$auc.pi,df$auc.lscv.bcv1)$p.value
  val[4] <- wilcox.test(df$auc.pi,df$auc.lscv.ns)$p.value
  
  val[5] <- wilcox.test(df$auc.lscv,df$auc.lscv.RN)$p.value
  val[6] <- wilcox.test(df$auc.lscv,df$auc.lscv.bcv1)$p.value
  val[7] <- wilcox.test(df$auc.lscv,df$auc.lscv.ns)$p.value
  
  val[8] <- wilcox.test(df$auc.lscv.RN,df$auc.lscv.bcv1)$p.value
  val[9] <- wilcox.test(df$auc.lscv.RN,df$auc.lscv.ns)$p.value
  
  val[10] <- wilcox.test(df$auc.bcv1,df$auc.lscv.ns)$p.value
}

### AUC Calculations
## All Data
# Load data
load(file=paste0(temp,"/EstimatesAllPI.R"))
load(file=paste0(temp,"/EstimatesAllLSCV.R"))
load(file=paste0(temp,"/EstimatesAllLSCVRN.R"))
load(file=paste0(temp,"/EstimatesAllBCV1.R"))
load(file=paste0(temp,"/EstimatesAllNS.R"))

# Bootstrap CIs
bs.all <- bootstrap.auc(event.type="all", estimates.all.pi, estimates.all.lscv, estimates.all.lscv.RN, estimates.all.bcv1, estimates.all.ns)

ci.all.pi <- bs.ci(bs.all$auc.pi)
ci.all.lscv <- bs.ci(bs.all$auc.lscv)
ci.all.lscv.RN <- bs.ci(bs.all$auc.lscv.RN)
ci.all.bcv1 <- bs.ci(bs.all$auc.bcv1)
ci.all.ns <- bs.ci(bs.all$auc.ns)

# KW on all but LSCV
x = c(bs.all$auc.pi, bs.all$auc.lscv.RN, bs.all$auc.bcv1, bs.all$auc.ns)
g = c(rep(1,B),rep(2,B),rep(3,B),rep(4,B))
ktest = kruskal.test(x,g)
ktest$statistic
ktest$p.value

# Pairwise Comparisons
## Wilcoxon rank-sum tests
p <- wilcox.auc(bs.all)

## Original pvalues
p

## Adjusted pvalues
p.adjust(p, method="holm")

# Combine AUC Calculations & Save
cis.all.combined <- rbind(ci.all.pi, ci.all.lscv, ci.all.lscv.RN, ci.all.bcv1, ci.all.ns)
colnames(cis.all.combined) <- c("LB", "Average","UB")
rownames(cis.all.combined) <- c("Plug-In","LSCV","LSCVRN","BCV2","NS")
write.xlsx(cis.all.combined, file=paste0(output,"/AUC CIs.xlsx"), sheetName="CIs-All", col.names=TRUE, row.names=TRUE, append=FALSE)

## Battles
# Load data
load(file=paste0(temp,"/EstimatesBattlesPI.R"))
load(file=paste0(temp,"/EstimatesBattlesLSCV.R"))
load(file=paste0(temp,"/EstimatesBattlesLSCVRN.R"))
load(file=paste0(temp,"/EstimatesBattlesBCV1.R"))
load(file=paste0(temp,"/EstimatesBattlesNS.R"))

# Bootstrap CIs
bs.b <- bootstrap.auc(event.type="B", estimates.b.pi, estimates.b.lscv, estimates.b.lscv.RN, estimates.b.bcv1, estimates.b.ns)

ci.b.pi <- bs.ci(bs.b$auc.pi)
ci.b.lscv <- bs.ci(bs.b$auc.lscv)
ci.b.lscv.RN <- bs.ci(bs.b$auc.lscv.RN)
ci.b.bcv1 <- bs.ci(bs.b$auc.bcv1)
ci.b.ns <- bs.ci(bs.b$auc.ns)

# KW on all but LSCV
x = c(bs.b$auc.pi, bs.b$auc.lscv.RN, bs.b$auc.bcv1, bs.b$auc.ns)
g = c(rep(1,B),rep(2,B),rep(3,B),rep(4,B))
ktest = kruskal.test(x,g)
ktest$statistic
ktest$p.value

# Pairwise Comparisons
## Wilcoxon rank-sum tests
p <- wilcox.auc(bs.b)

## Original pvalues
p

## Adjusted pvalues
p.adjust(p, method="holm")

# Combine AUC Calculations & Save
cis.b.combined <- rbind(ci.b.pi, ci.b.lscv, ci.b.lscv.RN, ci.b.bcv1, ci.b.ns)
colnames(cis.b.combined) <- c("LB: 1%", "Average","UB: 99%")
rownames(cis.b.combined) <- c("Plug-In","LSCV","LSCVRN","BCV2","NS")
write.xlsx(cis.b.combined, file=paste0(output,"/AUC CIs.xlsx"), sheetName="CIs-Battles", col.names=TRUE, row.names=TRUE, append=TRUE)

## Riots
# Load data
load(file=paste0(temp,"/EstimatesRiotsPI.R"))
load(file=paste0(temp,"/EstimatesRiotsLSCV.R"))
load(file=paste0(temp,"/EstimatesRiotsLSCVRN.R"))
load(file=paste0(temp,"/EstimatesRiotsBCV1.R"))
load(file=paste0(temp,"/EstimatesRiotsNS.R"))

# Bootstrap CIs
bs.r <- bootstrap.auc(event.type="all", estimates.r.pi, estimates.r.lscv, estimates.r.lscv.RN, estimates.r.bcv1, estimates.r.ns)

ci.r.pi <- bs.ci(bs.r$auc.pi)
ci.r.lscv <- bs.ci(bs.r$auc.lscv)
ci.r.lscv.RN <- bs.ci(bs.r$auc.lscv.RN)
ci.r.bcv1 <- bs.ci(bs.r$auc.bcv1)
ci.r.ns <- bs.ci(bs.r$auc.ns)

# KW on all but LSCV
x = c(bs.r$auc.pi, bs.r$auc.lscv.RN, bs.r$auc.bcv1, bs.r$auc.ns)
g = c(rep(1,B),rep(2,B),rep(3,B),rep(4,B))
ktest = kruskal.test(x,g)
ktest$statistic
ktest$p.value

# Pairwise Comparisons
## Wilcoxon rank-sum tests
p <- wilcox.auc(bs.r)

## Original pvalues
p

## Adjusted pvalues
p.adjust(p, method="holm")

# Combine AUC Calculations & Save
cis.r.combined <- rbind(ci.r.pi, ci.r.lscv, ci.r.lscv.RN, ci.r.bcv1, ci.r.ns)
colnames(cis.r.combined) <- c("LB: 1%", "Average","UB: 99%")
rownames(cis.r.combined) <- c("Plug-In","LSCV","LSCVRN","BCV2","NS")
write.xlsx(cis.r.combined, file=paste0(output,"/AUC CIs.xlsx"), sheetName="CIs-Riots", col.names=TRUE, row.names=TRUE, append=TRUE)

## Violence Against Civilians
# Load data
load(file=paste0(temp,"/EstimatesVACPI.R"))
load(file=paste0(temp,"/EstimatesVACLSCV.R"))
load(file=paste0(temp,"/EstimatesVACLSCVRN.R"))
load(file=paste0(temp,"/EstimatesVACBCV1.R"))
load(file=paste0(temp,"/EstimatesVACNS.R"))

# Bootstrap CIs
bs.v <- bootstrap.auc(event.type="all", estimates.v.pi, estimates.v.lscv, estimates.v.lscv.RN, estimates.v.bcv1, estimates.v.ns)

ci.v.pi <- bs.ci(bs.v$auc.pi)
ci.v.lscv <- bs.ci(bs.v$auc.lscv)
ci.v.lscv.RN <- bs.ci(bs.v$auc.lscv.RN)
ci.v.bcv1 <- bs.ci(bs.v$auc.bcv1)
ci.v.ns <- bs.ci(bs.v$auc.ns)

# KW on all but LSCV
x = c(bs.v$auc.pi, bs.v$auc.lscv.RN, bs.v$auc.bcv1, bs.v$auc.ns)
g = c(rep(1,B),rep(2,B),rep(3,B),rep(4,B))
ktest = kruskal.test(x,g)
ktest$statistic
ktest$p.value

# Pairwise Comparisons
## Wilcoxon rank-sum tests
p <- wilcox.auc(bs.v)

## Original pvalues
p

## Adjusted pvalues
p.adjust(p, method="holm")

# Combine AUC Calculations & Save
cis.v.combined <- rbind(ci.v.pi, ci.v.lscv, ci.v.lscv.RN, ci.v.bcv1, ci.v.ns)
colnames(cis.v.combined) <- c("LB: 1%", "Average","UB: 99%")
rownames(cis.v.combined) <- c("Plug-In","LSCV","LSCVRN","BCV2","NS")
write.xlsx(cis.v.combined, file=paste0(output,"/AUC CIs.xlsx"), sheetName="CIs-VAC", col.names=TRUE, row.names=TRUE, append=TRUE)
sink()